import { useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { Icon } from '@/components/ui';
import { palette, shadow } from '@/constants/theme';
import { schools } from '@/data/content';
import { openExternalLink } from '@/utils/openExternalLink';

const tabs = ['Overview', 'Requirements', 'Community', 'Updates'];
const requirements = [
  { title: 'Core application', items: ['LSAC Credential Assembly Service report', 'Completed JD application form', 'Application fee or approved waiver'] },
  { title: 'Written materials', items: ['Personal statement', 'Résumé', 'Character and fitness disclosures', 'Optional statements, if applicable'] },
  { title: 'Academic records & testing', items: ['All undergraduate and graduate transcripts', 'Accepted admission test score', 'Two recommendation letters'] },
];

export default function SchoolProfile() {
  const { id, tab } = useLocalSearchParams<{ id: string; tab?: string }>();
  const school = useMemo(() => schools.find((item) => item.id === id) ?? schools[0], [id]);
  const [active, setActive] = useState(tab && tabs.includes(tab) ? tab : 'Overview');
  const [open, setOpen] = useState('Core application');
  return (
    <ScrollView style={styles.screen} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} contentInsetAdjustmentBehavior="never">
      <View style={[styles.cover, { backgroundColor: school.color }]}>
        <View style={styles.coverGlow} /><View style={styles.coverMark}><Text style={[styles.coverMarkText, { color: school.color }]}>{school.initials}</Text></View>
      </View>
      <View style={styles.identity}>
        <View style={styles.nameRow}><View style={styles.nameText}><Text style={styles.name}>{school.name}</Text><View style={styles.verified}><Icon ios="checkmark.seal.fill" android="verified" size={16} color={palette.green} /><Text style={styles.verifiedText}>ABA approved</Text></View></View><Pressable style={styles.save}><Icon ios="bookmark" android="bookmark_border" size={20} color={palette.ink} /></Pressable></View>
        <Text style={styles.location}>{school.location} · {school.format.join(' & ')}</Text><Text style={styles.blurb}>{school.blurb}</Text>
        <View style={styles.actions}><Pressable onPress={() => openExternalLink(school.website, `${school.shortName} admissions`)} style={styles.primary}><Text style={styles.primaryText}>Official admissions site</Text><Icon ios="arrow.up.right" android="open_in_new" size={14} color="white" /></Pressable><Pressable style={styles.secondary}><Icon ios="square.and.arrow.up" android="share" size={17} color={palette.ink} /></Pressable></View>
      </View>

      <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.tabs} contentContainerStyle={styles.tabContent}>
        {tabs.map((item) => <Pressable key={item} onPress={() => setActive(item)} style={[styles.tab, active === item && styles.tabActive]}><Text style={[styles.tabText, active === item && styles.tabTextActive]}>{item}</Text></Pressable>)}
      </ScrollView>

      {active === 'Overview' ? <Overview school={school} /> : null}
      {active === 'Requirements' ? <View style={styles.section}><Text style={styles.sectionTitle}>Application checklist</Text><Text style={styles.sectionIntro}>Use this as a planning guide and verify every item on the official application.</Text>{requirements.map((group) => { const expanded = open === group.title; return <Pressable key={group.title} onPress={() => setOpen(expanded ? '' : group.title)} style={styles.accordion}><View style={styles.accordionTitle}><Text style={styles.accordionText}>{group.title}</Text><Icon ios={expanded ? 'chevron.up' : 'chevron.down'} android={expanded ? 'expand_less' : 'expand_more'} size={16} color={palette.inkMuted} /></View>{expanded ? <View style={styles.items}>{group.items.map((item) => <View key={item} style={styles.item}><View style={styles.check}><Icon ios="checkmark" android="check" size={11} color={palette.green} /></View><Text style={styles.itemText}>{item}</Text></View>)}</View> : null}</Pressable>; })}</View> : null}
      {active === 'Community' ? <Community color={school.color} /> : null}
      {active === 'Updates' ? <Updates school={school.shortName} /> : null}
      <Text style={styles.disclaimer}>Sample planning data only. Statistics and deadlines change; confirm all details with the school and current ABA disclosures.</Text>
    </ScrollView>
  );
}

function Overview({ school }: { school: (typeof schools)[number] }) {
  return <View style={styles.section}><Text style={styles.sectionTitle}>At a glance</Text><View style={styles.metrics}><Metric label="Median LSAT" value={school.medianLsat} /><Metric label="Acceptance" value={school.acceptance} /><Metric label="Deadline" value={school.deadline} /></View><Text style={styles.sectionTitle}>Application pathways</Text><View style={styles.pills}>{[...school.tests, ...school.schedule, ...school.format].map((item) => <View key={item} style={styles.pill}><Icon ios="checkmark" android="check" size={11} color={palette.green} /><Text style={styles.pillText}>{item}</Text></View>)}</View><Text style={styles.sectionTitle}>Useful links</Text>{['JD admissions & requirements', 'Tuition and financial aid', 'ABA required disclosures', 'Virtual campus tour'].map((label) => <Pressable key={label} onPress={() => openExternalLink(school.website, label)} style={styles.linkRow}><Text style={styles.linkLabel}>{label}</Text><Icon ios="arrow.up.right" android="open_in_new" size={15} color={palette.green} /></Pressable>)}</View>;
}
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
function Community({ color }: { color: string }) { const people = [['Admissions team', 'Official guidance and application questions', 'person.crop.circle.badge.questionmark'], ['Faculty', 'Academic programs and areas of study', 'person.2'], ['Current students', 'The student experience, in their words', 'graduationcap'], ['Alumni', 'Career paths and community stories', 'briefcase']]; return <View style={styles.section}><Text style={styles.sectionTitle}>Meet the community</Text><Text style={styles.sectionIntro}>Use verified channels and respect each person’s preferred way to connect.</Text>{people.map(([title, body, icon]) => <Pressable key={title} style={styles.person}><View style={[styles.personIcon, { backgroundColor: `${color}14` }]}><Icon ios={icon} android="person" color={color} /></View><View style={styles.personText}><Text style={styles.personTitle}>{title}</Text><Text style={styles.personBody}>{body}</Text></View><Icon ios="chevron.right" android="chevron_right" size={16} color="#9AA7A1" /></Pressable>)}</View>; }
function Updates({ school }: { school: string }) { return <View style={styles.section}><Text style={styles.sectionTitle}>Latest from {school}</Text>{['Admissions office hours for prospective students', 'What to know before submitting your application', 'Student voices: choosing the right JD program'].map((title, i) => <View key={title} style={styles.update}><Text style={styles.updateType}>{i === 0 ? 'EVENT' : 'POST'}</Text><Text style={styles.updateTitle}>{title}</Text><Text style={styles.updateMeta}>{i + 2} days ago · Official source</Text></View>)}</View>; }

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: palette.canvas }, content: { paddingBottom: 50 }, cover: { height: 220, justifyContent: 'flex-end', paddingHorizontal: 20, overflow: 'hidden' }, coverGlow: { position: 'absolute', width: 280, height: 280, borderRadius: 140, backgroundColor: '#FFFFFF14', right: -80, top: -100 }, coverMark: { width: 82, height: 82, borderRadius: 24, backgroundColor: palette.surface, alignItems: 'center', justifyContent: 'center', marginBottom: -34, borderWidth: 4, borderColor: 'white', ...shadow }, coverMarkText: { fontSize: 24, fontWeight: '900' }, identity: { backgroundColor: palette.surface, paddingHorizontal: 20, paddingTop: 51, paddingBottom: 20 }, nameRow: { flexDirection: 'row', alignItems: 'flex-start' }, nameText: { flex: 1, paddingRight: 12 }, name: { color: palette.ink, fontSize: 24, lineHeight: 29, fontWeight: '800', letterSpacing: -0.5 }, verified: { flexDirection: 'row', gap: 5, alignItems: 'center', marginTop: 7 }, verifiedText: { color: palette.green, fontSize: 11, fontWeight: '800' }, save: { width: 42, height: 42, borderRadius: 21, borderWidth: 1, borderColor: palette.line, alignItems: 'center', justifyContent: 'center' }, location: { color: palette.inkMuted, fontSize: 13, marginTop: 11 }, blurb: { color: palette.ink, fontSize: 14, lineHeight: 21, marginTop: 11 }, actions: { flexDirection: 'row', gap: 9, marginTop: 18 }, primary: { flex: 1, height: 46, borderRadius: 14, backgroundColor: palette.greenButton, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 7 }, primaryText: { color: 'white', fontWeight: '800', fontSize: 13 }, secondary: { width: 46, height: 46, borderRadius: 14, borderWidth: 1, borderColor: palette.line, alignItems: 'center', justifyContent: 'center' },
  tabs: { backgroundColor: palette.surface, borderTopWidth: 1, borderColor: palette.line }, tabContent: { paddingHorizontal: 13 }, tab: { paddingHorizontal: 12, paddingVertical: 15, borderBottomWidth: 2, borderBottomColor: 'transparent' }, tabActive: { borderBottomColor: palette.green }, tabText: { color: palette.inkMuted, fontSize: 13, fontWeight: '700' }, tabTextActive: { color: palette.green }, section: { paddingHorizontal: 20, paddingTop: 24 }, sectionTitle: { color: palette.ink, fontSize: 19, fontWeight: '800', marginBottom: 13, marginTop: 5 }, sectionIntro: { color: palette.inkMuted, fontSize: 12, lineHeight: 18, marginTop: -7, marginBottom: 13 }, metrics: { flexDirection: 'row', gap: 9, marginBottom: 24 }, metric: { flex: 1, backgroundColor: palette.surface, paddingVertical: 15, borderRadius: 16, alignItems: 'center', borderWidth: 1, borderColor: palette.line }, metricValue: { color: palette.ink, fontSize: 18, fontWeight: '900' }, metricLabel: { color: palette.inkMuted, fontSize: 9, marginTop: 4 }, pills: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 24 }, pill: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: palette.mintSoft, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 7 }, pillText: { color: palette.greenDark, fontSize: 11, fontWeight: '700' }, linkRow: { height: 49, backgroundColor: palette.surface, paddingHorizontal: 14, borderRadius: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8, borderWidth: 1, borderColor: palette.line }, linkLabel: { color: palette.ink, fontSize: 13, fontWeight: '700' },
  accordion: { backgroundColor: palette.surface, borderRadius: 16, padding: 16, marginBottom: 10, borderWidth: 1, borderColor: palette.line }, accordionTitle: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, accordionText: { color: palette.ink, fontSize: 14, fontWeight: '800' }, items: { paddingTop: 13, gap: 10 }, item: { flexDirection: 'row', alignItems: 'center', gap: 9 }, check: { width: 20, height: 20, borderRadius: 10, backgroundColor: palette.mintSoft, alignItems: 'center', justifyContent: 'center' }, itemText: { flex: 1, color: palette.inkMuted, fontSize: 12, lineHeight: 17 }, person: { backgroundColor: palette.surface, borderRadius: 17, padding: 14, marginBottom: 10, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: palette.line }, personIcon: { width: 46, height: 46, borderRadius: 14, justifyContent: 'center', alignItems: 'center', marginRight: 12 }, personText: { flex: 1 }, personTitle: { color: palette.ink, fontSize: 14, fontWeight: '800' }, personBody: { color: palette.inkMuted, fontSize: 11, lineHeight: 16, marginTop: 3 }, update: { backgroundColor: palette.surface, borderRadius: 17, padding: 16, marginBottom: 10, borderWidth: 1, borderColor: palette.line }, updateType: { color: palette.green, fontSize: 9, fontWeight: '900', letterSpacing: 0.8 }, updateTitle: { color: palette.ink, fontSize: 15, lineHeight: 20, fontWeight: '800', marginTop: 6 }, updateMeta: { color: palette.inkMuted, fontSize: 10, marginTop: 8 }, disclaimer: { color: '#929E98', fontSize: 10, lineHeight: 15, textAlign: 'center', paddingHorizontal: 32, marginTop: 28 },
});
